apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-ui
  labels:
    app: ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: login-ui
  template:
    metadata:
      labels:
        app: login-ui
    spec:
      containers:
      - name: front
        image: frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: login-ui
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000